
version: "3.8"

services:
  frontend:
    build: 
      context: /workspaces/dev/frontend
      dockerfile: /workspaces/CI-CD/frontend/Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - /workspaces/dev/frontend:/app
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
  backend:
    build:
      context: /workspaces/dev/backend
      dockerfile: /workspaces/CI-CD/backend/Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - /workspaces/dev/backend:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - API_KEY=${API_KEY}
    command: ["npm", "run", "dev"]